device: cuda
model:
  architecture:
    encoder:
        conv:
            - Linear:
                args: [784, 512]
                bias: False
            - Tanh:
            - Linear:
                args: [512, 256]
                bias: False
            - Tanh:
            - Flatten:
        mean:
            - Linear:
                args: [256, 32]
                bias: False
        log_var:
            - Linear:
                args: [256, 32]
                bias: False
    decoder:
        - Linear:
            args: [32, 256]
            bias: False
        - Tanh:
        - Linear:
            args: [256, 512]
            bias: False
        - Tanh:
        - Linear:
            args: [512, 784]
            bias: False
        - Sigmoid:
test:
  batch_size: 256
  n_components: 2
  model_path: ./pretrained/model_90.pt
  results_path: ./inverse_results